### ISSUE TITLE
Feels Kinda Empty.

### ISSUE THREAD

**Issue by SashQuasher** [kerbero1994/Assigment-MagmaHackers-First#10]
In genereal the design it's Ok. In my opinion You could use some more images and a more attractive text in the "Home" section. In more personal thinking, I feel that the info is kinda disordered, but that's just my OCD though XD. In the backend i just think you could Ident it better, using Prettify, but again, i guess that's my OCD speaking.

Nice work, keep it up. 👍

**Comment by kerbero1994** [comment]
Hello, good evening, I usually use the Atom Beautify packages to avoid this, but this time I forget it completely, and in effect now that I see it I think I will add some extra images to improve the design thanks for the comments.
