### ISSUE TITLE
Assignment review from magmahackers

### ISSUE THREAD

**Issue by ulisesac4** [kerbero1994/Assigment-MagmaHackers-First#2]
Hi Eduardo, let me go into detail in your review:

About your code, I find it fine, I do not have anything to say.

About your design I have some things to say:

1. The first thing is that I do not like the layout of your photo, I believe that it should be below your navbar, but it is my personal opinion, you can ignore this.

2. Not color consistency in text blocks: I do not believe that you should be changing the color of your text blocks, that reflects an inconsistent presentation. Choose only black or blue, but only one.

3. Grammar issues: It is written "project" and "professional".

4. You need a little bit of vertical padding in your footer, because your text is touching the ceiling of the footer.

**Comment by kerbero1994** [comment]
Hello, good evening, thank you for your feedback, the grammatical errors, the inconsistency in the colors and the padding of the footer, are careless of the ones that I did not notice thank you, that happens when you modify with the browser tools and do not check if Saved the changes XD.
