### ISSUE TITLE
Orthography

### ISSUE THREAD

**Issue by tzohpilotl** [kerbero1994/Assigment-MagmaHackers-First#4]
Good evening, Eduardo. First of all, I will say that is really nice to know you a little better because you are such an interesting person. Now, given that we both enjoy reading and writing, you will understand why my recommendation is about orthography. Maybe you could use a  spell checker? Anyways, keep up the good work buddy, see you around!

**Comment by kerbero1994** [comment]
Hi, good evening, thanks for your feedback, I still have rookie errors when I write in English, I'm already using grammarly to prevent this from being repeated XD.
