### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by maribel-arac** [kerbero1994/Assigment-MagmaHackers-First#8]
Hello well, I'm learning programming and in general I think your code is ok but found some mistakes about spelling; for the sentence: 'I am perfected my English and started with French', it will sound better: I'm improvising my English and recently started French'.

**Comment by kerbero1994** [comment]
Hi, good evening, thanks for your feedback, I still have rookie errors when I write in English, I'm already using grammarly to prevent this from being repeated XD.
