### ISSUE TITLE
A few things to say

### ISSUE THREAD

**Issue by salvadorJimenez** [kerbero1994/Assigment-MagmaHackers-First#9]
Nice job, you create a website without a framework, this is good and bad becouse you spend much time and effort to do it, but the good thing is that you learn and the next time will be faster.

So if you can and want, you could inbestigate how use Bootstrap framework and you will see that some things you can do it faster and easy. So the problem here is not with your code, is with design, so maybe you dont want to be a front end developer, but you have to know about style, so I propose you learn about front end and css and css freameworks.

All the information is good and really of interest but could be better if you aply a better design.

So btw good job and try to improve your skills. I'm not the best web dev but whatever you need contact me and if i can help you, i'll do it.

**Comment by kerbero1994** [comment]
Hello, good evening, thank you for your recommendations, for now, I am studying some Frameworks for the frontend to streamline my developments and improve in this area, I appreciate your offer and likewise if I can help you with something.
